const CFG=window.QUINIELA_CONFIG||{},$=id=>document.getElementById(id);let adminUsername='',adminPassword='',state={matches:[],results:[],leaderboard:[],users:[],submissions:[],audit:[]};
const STORE_KEYS=['quinielaUsers','quinielaCurrentUser','quinielaSubmissions','quinielaMatches','quinielaResults','quinielaAudit','quinielaLeaderboard','quinielaPlayers','quinielaPredictions','quinielaUser','quinielaSession','quinielaDrafts'];
const store={get:k=>JSON.parse(localStorage.getItem(k)||'null'),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(iso){return iso?new Intl.DateTimeFormat('es-CR',{dateStyle:'medium',timeStyle:'short',timeZone:CFG.TIMEZONE||'America/Costa_Rica'}).format(new Date(iso)):''}
async function loadJson(p){return fetch(p,{cache:'no-store'}).then(r=>r.json())}
async function api(p){const body={...p,adminUsername,adminPassword};if(CFG.MODE!=='production')return demoAdmin(body);return fetch(CFG.GAS_WEBAPP_URL,{method:'POST',body:JSON.stringify(body)}).then(r=>r.json())}
function notice(m){$('adminNotice').textContent=m;$('adminNotice').classList.remove('hidden')}
function cleanLocalTournament(resetMode='playersOnly'){STORE_KEYS.forEach(k=>{if(resetMode==='all'||!['quinielaMatches','quinielaResults'].includes(k))store.del(k)});Object.keys(localStorage).filter(k=>k.startsWith('draft-')||k.startsWith('quinielaOld')||k.startsWith('quinielaDemo')).forEach(k=>localStorage.removeItem(k));if(resetMode==='all')store.del('quinielaResults')}
function calcBoard(users,subs,results){const rmap=Object.fromEntries((results||[]).map(r=>[r.matchId,r])),versions={};subs.forEach(s=>versions[s.playerNumber]=(versions[s.playerNumber]||0)+1);const latest={};subs.filter(s=>s.validBeforeDeadline).forEach(s=>{if(!latest[s.playerNumber]||new Date(s.timestamp)>new Date(latest[s.playerNumber].timestamp))latest[s.playerNumber]=s});return Object.values(latest).map(s=>{let totalPoints=0,exactHits=0,winnerHits=0;Object.entries(s.predictions||{}).forEach(([mid,p])=>{let r=rmap[mid];if(!r||r.status!=='terminado'||!r.winner)return;if(String(p.winner)===String(r.winner)){winnerHits++;let ex=Number(p.scoreA)===Number(r.goalsA)&&Number(p.scoreB)===Number(r.goalsB);if(ex){exactHits++;totalPoints+=3}else totalPoints+=1}});return{playerNumber:s.playerNumber,playerName:s.playerName,totalPoints,exactHits,winnerHits,versions:versions[s.playerNumber]||1,lastValidSubmission:s.timestamp}}).sort((a,b)=>b.totalPoints-a.totalPoints||b.exactHits-a.exactHits||b.winnerHits-a.winnerHits).map((r,i)=>({...r,position:i+1}))}
async function demoAdmin(p){let sample=await loadJson('data/demo-state.json'),users=store.get('quinielaUsers')||[],submissions=store.get('quinielaSubmissions')||[],matches=store.get('quinielaMatches')||sample.matches,results=store.get('quinielaResults')||[],audit=store.get('quinielaAudit')||[];if(p.action==='adminLogin'){return p.adminUsername==='Amargo'&&(p.adminPassword||'').length>=4?{ok:true}:{ok:false,error:'Credenciales de administrador inválidas.'}}if(p.action==='getAdminState')return{ok:true,users,matches,results,submissions,leaderboard:calcBoard(users,submissions,results),audit,deadline:CFG.DEADLINE};if(p.action==='saveMatches'){store.set('quinielaMatches',p.matches);audit.push({timestamp:new Date().toISOString(),action:'saveMatches',playerNumber:'admin',payloadJson:JSON.stringify({count:p.matches.length})});store.set('quinielaAudit',audit);return{ok:true,message:'Equipos guardados'};}if(p.action==='saveResults'){store.set('quinielaResults',p.results);audit.push({timestamp:new Date().toISOString(),action:'saveResults',playerNumber:'admin',payloadJson:JSON.stringify({count:p.results.length})});store.set('quinielaAudit',audit);return{ok:true,message:'Resultados guardados',leaderboard:calcBoard(users,submissions,p.results)};}if(p.action==='resetTournamentData'){cleanLocalTournament(p.resetMode);if(p.resetMode==='all')results=[];audit.push({timestamp:new Date().toISOString(),action:'resetTournamentData',playerNumber:'admin',payloadJson:JSON.stringify({resetMode:p.resetMode})});store.set('quinielaAudit',audit);return{ok:true,message:p.resetMode==='all'?'Torneo limpiado incluyendo resultados.':'Jugadores y predicciones limpiados.'}}if(p.action==='syncTournamentData'){audit.push({timestamp:new Date().toISOString(),action:'syncTournamentData',playerNumber:'admin',payloadJson:JSON.stringify({mode:'demo'})});store.set('quinielaAudit',audit);return{ok:true,message:'Sincronización registrada en demo. En producción se usa la fuente configurada.'}}if(p.action==='recalculate')return{ok:true,message:'Tabla recalculada',leaderboard:calcBoard(users,submissions,results)};return{ok:false,error:'Acción no soportada'}}
async function login(){adminUsername=$('adminUsername').value.trim();adminPassword=$('adminPassword').value;let r=await api({action:'adminLogin'});if(!r.ok){$('adminLoginNotice').textContent=r.error;$('adminLoginNotice').classList.remove('hidden');return}$('adminLoginCard').classList.add('hidden');$('adminPanel').classList.remove('hidden');await loadState()}
async function loadState(){let r=await api({action:'getAdminState'});if(!r.ok)return notice(r.error);state=r;renderAll()}
function renderAll(){renderPlayers();renderResults();renderMatches();renderTable();renderAudit();renderExport()}
function renderPlayers(){let counts={};(state.submissions||[]).forEach(s=>counts[s.playerNumber]=(counts[s.playerNumber]||0)+1);$('tab-players').innerHTML=`<h2>Jugadores</h2><div class="actions"><button id="resetPlayersBtn">Limpiar solo jugadores y predicciones</button><button id="resetAllBtn">Limpiar todo incluyendo resultados</button></div><p class="muted">Para limpiar se pedirá escribir exactamente LIMPIAR. La configuración de equipos se conserva salvo que elijas limpiar todo.</p><table class="leaderboard-table"><thead><tr><th>Número</th><th>Nombre</th><th>Estado</th><th>Fecha de registro</th><th>Último ingreso</th><th>Cantidad de versiones enviadas</th><th>Última quiniela válida</th></tr></thead><tbody>${(state.users||[]).map(u=>{let last=(state.submissions||[]).filter(s=>s.playerNumber===u.playerNumber&&s.validBeforeDeadline).at(-1);return`<tr><td>${esc(u.playerNumber)}</td><td>${esc(u.playerName)}</td><td>${esc(u.status)}</td><td>${fmt(u.createdAt)}</td><td>${fmt(u.lastLogin)}</td><td>${counts[u.playerNumber]||0}</td><td>${fmt(last?.timestamp)}</td></tr>`}).join('')||'<tr><td colspan="7">Sin jugadores registrados.</td></tr>'}</tbody></table>`;$('resetPlayersBtn').onclick=()=>resetTournament('playersOnly');$('resetAllBtn').onclick=()=>resetTournament('all')}
function renderResults(){$('tab-results').innerHTML=`<h2>Resultados</h2><div class="match-cards">${(state.matches||[]).map(m=>{let r=(state.results||[]).find(x=>x.matchId===m.matchId)||{};return`<div class="match-card"><h3>${esc(m.matchId)}</h3><p>${esc(m.teamA||'Pendiente por definir')} vs ${esc(m.teamB||'Pendiente por definir')}</p><label>Goles A<input type="number" min="0" data-res="${m.matchId}" data-field="goalsA" value="${esc(r.goalsA??'')}"></label><label>Goles B<input type="number" min="0" data-res="${m.matchId}" data-field="goalsB" value="${esc(r.goalsB??'')}"></label><label>Clasificado<select data-res="${m.matchId}" data-field="winner"><option></option><option ${r.winner===m.teamA?'selected':''}>${esc(m.teamA||'')}</option><option ${r.winner===m.teamB?'selected':''}>${esc(m.teamB||'')}</option></select></label><label>Estado<select data-res="${m.matchId}" data-field="status"><option ${r.status!=='terminado'?'selected':''}>pendiente</option><option ${r.status==='terminado'?'selected':''}>terminado</option></select></label></div>`}).join('')}</div><button id="saveResultsBtn" class="primary">Guardar resultados</button>`;$('saveResultsBtn').onclick=saveResults}
function renderMatches(){$('tab-matches').innerHTML=`<h2>Clasificados / equipos</h2><p class="muted">Podés editar equipos manualmente o sincronizarlos desde la fuente configurada en producción.</p><div class="actions"><button id="syncDataBtn">Actualizar partidos/clasificados</button></div><div class="match-cards">${(state.matches||[]).map(m=>`<div class="match-card"><label>matchId<input data-match="${m.matchId}" data-field="matchId" value="${esc(m.matchId)}" readonly></label><label>Ronda<input data-match="${m.matchId}" data-field="round" value="${esc(m.round||'')}"></label><label>Equipo A<input data-match="${m.matchId}" data-field="teamA" value="${esc(m.teamA||'')}"></label><label>Equipo B<input data-match="${m.matchId}" data-field="teamB" value="${esc(m.teamB||'')}"></label></div>`).join('')}</div><button id="saveMatchesBtn" class="primary">Guardar equipos</button>`;$('saveMatchesBtn').onclick=saveMatches;$('syncDataBtn').onclick=syncData}
function renderTable(){let rows=state.leaderboard||[];$('tab-table').innerHTML=`<h2>Tabla</h2><table class="leaderboard-table"><thead><tr><th>Puesto</th><th>Número</th><th>Nombre</th><th>Puntos</th><th>Marcadores exactos</th><th>Ganadores acertados</th><th>Versiones enviadas</th></tr></thead><tbody>${rows.map(r=>`<tr class="rank-${r.position}"><td>${r.position<=3?['🥇','🥈','🥉'][r.position-1]:r.position}</td><td>${esc(r.playerNumber)}</td><td>${esc(r.playerName)}</td><td>${r.totalPoints}</td><td>${r.exactHits}</td><td>${r.winnerHits}</td><td>${r.versions||''}</td></tr>`).join('')||'<tr><td colspan="7">Sin tabla.</td></tr>'}</tbody></table><button id="recalcBtn">Recalcular</button>`;$('recalcBtn').onclick=recalc}
function renderAudit(){$('tab-audit').innerHTML=`<h2>Auditoría</h2><table class="leaderboard-table"><thead><tr><th>Fecha</th><th>Acción</th><th>Jugador</th><th>Resumen</th></tr></thead><tbody>${(state.audit||[]).map(a=>{let detail='Movimiento registrado';try{let j=JSON.parse(a.payloadJson||'{}');detail=j.submissionId?`Registro ${j.submissionId} · versión ${j.version||''}`:j.count?`${j.count} elementos actualizados`:j.resetMode?`Limpieza: ${j.resetMode}`:'Movimiento registrado'}catch(e){}return`<tr><td>${fmt(a.timestamp)}</td><td>${esc(a.action)}</td><td>${esc(a.playerNumber||'')}</td><td>${esc(detail)}</td></tr>`}).join('')||'<tr><td colspan="4">Sin registros.</td></tr>'}</tbody></table>`}
function csv(name,rows){let blob=new Blob([rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}
function renderExport(){$('tab-export').innerHTML=`<h2>Exportar</h2><div class="actions"><button id="csvPlayers">Exportar jugadores CSV</button><button id="csvPredictions">Exportar predicciones CSV</button><button id="csvTable">Exportar tabla CSV</button></div>`;$('csvPlayers').onclick=()=>csv('jugadores.csv',[['Número','Nombre','Estado','Fecha de registro','Último ingreso'],...(state.users||[]).map(u=>[u.playerNumber,u.playerName,u.status,u.createdAt,u.lastLogin])]);$('csvPredictions').onclick=()=>csv('predicciones.csv',[['timestamp','submissionId','playerNumber','playerName','version','validBeforeDeadline','predictions'],...(state.submissions||[]).map(s=>[s.timestamp,s.submissionId,s.playerNumber,s.playerName,s.version,s.validBeforeDeadline,JSON.stringify(s.predictions||{})])]);$('csvTable').onclick=()=>csv('tabla.csv',[['Puesto','Número','Nombre','Puntos','Exactos','Ganadores'],...(state.leaderboard||[]).map(r=>[r.position,r.playerNumber,r.playerName,r.totalPoints,r.exactHits,r.winnerHits])])}
function collectMatches(){return state.matches.map(m=>{document.querySelectorAll(`[data-match="${m.matchId}"]`).forEach(el=>m[el.dataset.field]=el.value);return m})}
function collectResults(){let map={};document.querySelectorAll('[data-res]').forEach(el=>{map[el.dataset.res]||={matchId:el.dataset.res};map[el.dataset.res][el.dataset.field]=el.value});return Object.values(map)}
async function saveMatches(){let r=await api({action:'saveMatches',matches:collectMatches()});notice(r.message||r.error);await loadState()}
async function saveResults(){let r=await api({action:'saveResults',results:collectResults()});notice(r.message||r.error);await loadState()}
async function recalc(){let r=await api({action:'recalculate'});notice(r.message||r.error);await loadState()}
async function syncData(){let r=await api({action:'syncTournamentData'});notice(r.message||r.error);await loadState()}
async function resetTournament(resetMode){if(prompt('Para confirmar la acción Limpiar torneo, escribí exactamente LIMPIAR')!=='LIMPIAR')return notice('Limpieza cancelada.');let r=await api({action:'resetTournamentData',resetMode});notice(r.message||r.error);await loadState()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('primary'));b.classList.add('primary');document.querySelectorAll('.admin-tab').forEach(t=>t.classList.add('hidden'));$(`tab-${b.dataset.tab}`).classList.remove('hidden')});$('adminLoginBtn').onclick=login;
