const CFG=window.QUINIELA_CONFIG||{};
const $=id=>document.getElementById(id);let state={matches:[],results:[],leaderboard:[],lastSync:null},currentUser=null,playerPassword='',predictions={},bracketMatches=[];
const store={get:k=>JSON.parse(localStorage.getItem(k)||'null'),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};
async function loadJson(p){return fetch(p,{cache:'no-store'}).then(r=>r.json())}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(iso){return iso?new Intl.DateTimeFormat('es-CR',{dateStyle:'medium',timeStyle:'short',timeZone:CFG.TIMEZONE||'America/Costa_Rica'}).format(new Date(iso)):''}
function beforeDeadline(){return Date.now()<=new Date(state.deadline||CFG.DEADLINE).getTime()}
function resetLocalDemoData(){['quinielaUsers','quinielaCurrentUser','quinielaSubmissions','quinielaMatches','quinielaResults','quinielaAudit','quinielaLeaderboard','quinielaPlayers','quinielaPredictions','quinielaUser','quinielaSession','quinielaDrafts'].forEach(k=>store.del(k));Object.keys(localStorage).filter(k=>k.startsWith('draft-')||k.startsWith('quinielaOld')||k.startsWith('quinielaDemo')).forEach(k=>localStorage.removeItem(k))}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function api(p){if(CFG.MODE!=='production')return demoApi(p);return fetch(CFG.GAS_WEBAPP_URL,{method:'POST',body:JSON.stringify(p)}).then(r=>r.json())}
const roundOrder=['16avos de final','8vos de final','Cuartos de final','Semifinales','Tercer lugar','Final'];
const expectedRoundCounts={'16avos de final':16,'8vos de final':8,'Cuartos de final':4,'Semifinales':2,'Tercer lugar':1,'Final':1};
const shortRound=r=>({'16avos de final':'16avos','8vos de final':'8vos','Cuartos de final':'Cuartos','Semifinales':'Semis','Tercer lugar':'3er lugar','Final':'Final'}[r]||r||'Ronda');
function normalizeMatches(ms){return (ms||[]).map((m,i)=>({...m,order:m.order||i+1,sourceTypeA:m.sourceMatchA?'winner':(m.sourceTypeA||'static'),sourceTypeB:m.sourceMatchB?'winner':(m.sourceTypeB||'static')}))}
function getDisplayTeam(match,side){const suffix=side==='teamA'||side==='A'?'A':'B';const key=`team${suffix}`;return match?.[key]||match?.[`team${suffix}Source`]||'Pendiente por definir'}
function team(m,side){return getDisplayTeam(m,side)}
function realTeam(m,side){return m?.[side]||''}
function pickValue(m,side){return getDisplayTeam(m,side)}
function rebuildPredictedBracket(matches,preds){
  const map=Object.fromEntries(normalizeMatches(matches).map(m=>[String(m.matchId),{...m}]));
  const ordered=roundOrder.flatMap(r=>Object.values(map).filter(m=>m.round===r).sort((a,b)=>(a.order||0)-(b.order||0)));
  ordered.forEach(m=>{
    const p=preds[m.matchId];
    const validValues=[getDisplayTeam(m,'teamA'),getDisplayTeam(m,'teamB')];
    if(p?.winner&&!validValues.includes(p.winner)){delete p.winner; delete p.scoreA; delete p.scoreB}
    const w=p?.winner;
    if(!w)return;
    if(m.nextMatch&&m.nextSlot&&map[m.nextMatch])map[m.nextMatch][m.nextSlot]=w;
    if(m.loserNextMatch&&m.loserNextSlot&&map[m.loserNextMatch]){const a=getDisplayTeam(m,'teamA'),b=getDisplayTeam(m,'teamB');const loser=w===a?b:w===b?a:'';if(loser)map[m.loserNextMatch][m.loserNextSlot]=loser}
  });
  return roundOrder.flatMap(r=>Object.values(map).filter(m=>m.round===r).sort((a,b)=>(a.order||0)-(b.order||0)));
}
function rebuildBracketFromPredictions(){bracketMatches=rebuildPredictedBracket(state.matches,predictions);return bracketMatches;}
function completion(m){const p=predictions[m.matchId]||{},hasTeams=realTeam(m,'teamA')&&realTeam(m,'teamB'),scores=p.scoreA!==''&&p.scoreA!=null&&p.scoreB!==''&&p.scoreB!=null;if(!beforeDeadline())return{cls:'locked',txt:'Partido bloqueado'};if(scores&&p.winner)return{cls:'complete',txt:'Pronóstico completo'};if(p.winner||scores)return{cls:'warn',txt:'Pronóstico parcial'};if(!hasTeams)return{cls:'pending',txt:'Pendiente de equipos · Pendiente por definir'};return{cls:'pending',txt:'Pendiente'}}
function updateDraftStatus(txt='Cambios sin guardar'){const el=$('draftStatus'); if(el)el.textContent=txt}
function saveDraft(){if(!currentUser)return;store.set(`draft-${currentUser.playerNumber}`,{predictions,timestamp:new Date().toISOString()});updateDraftStatus('Guardado local')}
async function init(){state=CFG.MODE==='production'?{matches:await loadJson('data/matches.json').catch(()=>[]),lastSync:await loadJson('data/last-sync.json').catch(()=>null),results:[],leaderboard:[],deadline:CFG.DEADLINE}:await loadJson('data/demo-state.json');if(!state.lastSync)state.lastSync=await loadJson('data/last-sync.json').catch(()=>null);state.matches=normalizeMatches(state.matches);state.deadline=state.deadline||CFG.DEADLINE;
const s=store.get('quinielaCurrentUser');if(s){playerPassword=s.password||'';await enterApp(s,false)}}
function show(el,msg){el.textContent=msg;el.classList.remove('hidden')}
function hide(el){el.classList.add('hidden')}
async function demoApi(p){let users=store.get('quinielaUsers')||[],subs=store.get('quinielaSubmissions')||[],audit=store.get('quinielaAudit')||[],matches=store.get('quinielaMatches')||state.matches,results=store.get('quinielaResults')||state.results;if(p.action==='registerPlayer'){if(!p.playerName?.trim())return{ok:false,error:'El nombre es obligatorio.'};if(!p.playerNumber?.trim())return{ok:false,error:'El número de jugador es obligatorio.'};if((p.password||'').length<4)return{ok:false,error:'La contraseña debe tener mínimo 4 caracteres.'};if(users.some(u=>u.playerNumber===String(p.playerNumber)))return{ok:false,error:'Ese número de jugador ya existe.'};let u={createdAt:new Date().toISOString(),playerNumber:String(p.playerNumber),playerName:p.playerName.trim(),passwordHash:await hash(p.password),status:'activo',lastLogin:new Date().toISOString()};users.push(u);store.set('quinielaUsers',users);return{ok:true,playerNumber:u.playerNumber,playerName:u.playerName}}if(p.action==='loginPlayer'||p.action==='getPlayerState'){let u=users.find(u=>u.playerNumber===String(p.playerNumber));if(!u||u.passwordHash!==await hash(p.password||''))return{ok:false,error:'Número o contraseña incorrectos.'};u.lastLogin=new Date().toISOString();store.set('quinielaUsers',users);let mine=subs.filter(s=>s.playerNumber===u.playerNumber),valid=mine.filter(s=>s.validBeforeDeadline).at(-1);return{ok:true,playerNumber:u.playerNumber,playerName:u.playerName,player:{playerNumber:u.playerNumber,playerName:u.playerName},latestPrediction:valid?.predictions||null,history:mine,deadline:state.deadline,matches,results,leaderboard:calcBoard(users,subs,results)}}if(p.action==='submitPrediction'){let auth=await demoApi({action:'loginPlayer',playerNumber:p.playerNumber,password:p.password});if(!auth.ok)return auth;let valid=beforeDeadline(),version=subs.filter(s=>s.playerNumber===String(p.playerNumber)).length+1,rec={timestamp:new Date().toISOString(),submissionId:'LOCAL-'+crypto.randomUUID().slice(0,8).toUpperCase(),playerNumber:String(p.playerNumber),playerName:auth.playerName,predictions:p.predictions||{},validBeforeDeadline:valid,version};subs.push(rec);audit.push({timestamp:rec.timestamp,action:'submitPrediction',playerNumber:rec.playerNumber,payloadJson:JSON.stringify({submissionId:rec.submissionId,version})});store.set('quinielaSubmissions',subs);store.set('quinielaAudit',audit);return{ok:true,...rec,leaderboard:calcBoard(users,subs,results)}}return{ok:false,error:'Acción no soportada'}}
function calcBoard(users,subs,results){const rmap=Object.fromEntries((results||[]).map(r=>[r.matchId,r])),versions={};subs.forEach(s=>versions[s.playerNumber]=(versions[s.playerNumber]||0)+1);
const latest={};subs.filter(s=>s.validBeforeDeadline).forEach(s=>{if(!latest[s.playerNumber]||new Date(s.timestamp)>new Date(latest[s.playerNumber].timestamp))latest[s.playerNumber]=s});return Object.values(latest).map(s=>{let total=0,exactHits=0,winnerHits=0;Object.entries(s.predictions||{}).forEach(([mid,p])=>{let r=rmap[mid];if(!r||r.status!=='terminado'||!r.winner)return;if(String(p.winner)===String(r.winner)){winnerHits++;let ex=Number(p.scoreA)===Number(r.goalsA)&&Number(p.scoreB)===Number(r.goalsB);total+=ex?3:1;if(ex)exactHits++}});return{playerNumber:s.playerNumber,playerName:s.playerName,totalPoints:total,exactHits,winnerHits,versions:versions[s.playerNumber]||1,lastValidSubmission:s.timestamp}}).sort((a,b)=>b.totalPoints-a.totalPoints||b.exactHits-a.exactHits||b.winnerHits-a.winnerHits).map((r,i)=>({...r,position:i+1}))}
async function enterApp(user,persist=true){currentUser={playerNumber:String(user.playerNumber),playerName:user.playerName};if(persist)store.set('quinielaCurrentUser',{...currentUser,password:playerPassword});let res=await api({action:'getPlayerState',playerNumber:currentUser.playerNumber,password:playerPassword});if(res.ok){state={...state,matches:normalizeMatches(res.matches||state.matches),results:res.results||[],leaderboard:res.leaderboard||[],deadline:res.deadline||state.deadline};predictions=res.latestPrediction||store.get(`draft-${currentUser.playerNumber}`)?.predictions||{};renderHistory(res.history||[])}renderSyncInfo();$('authCard').classList.add('hidden');$('appView').classList.remove('hidden');$('playerBadge').textContent=`${currentUser.playerName} · #${currentUser.playerNumber}`;$('deadlineText').textContent=`Cierre: ${fmt(state.deadline)}`;renderAll()}
function renderAll(){renderAllRounds(rebuildBracketFromPredictions());renderProgress();renderForm();renderBracket();renderLeaderboard();renderSyncInfo()}
function renderSyncInfo(){const el=$('syncInfo');if(!el)return;const s=state.lastSync||{};el.innerHTML=`Datos actualizados: ${esc(s.lastSyncAt?fmt(s.lastSyncAt):'pendiente')} · Fuente: ${esc(s.source||'manual')} · ${esc(s.message||'Los equipos pendientes se completarán cuando FIFA los confirme.')}`}
function renderAllRounds(matches){return roundOrder.map(r=>{const ms=(matches||[]).filter(m=>m.round===r);return{round:r,matches:ms,count:ms.length,expected:expectedRoundCounts[r],alert:ms.length<expectedRoundCounts[r]}})}
function renderProgress(){let total=bracketMatches.length,done=bracketMatches.filter(m=>completion(m).cls==='complete').length;$('progressText').textContent=`Has completado ${done} de ${total} partidos`;$('progressBar').style.width=`${total?done/total*100:0}%`}
function renderForm(){const groups=renderAllRounds(bracketMatches);$('predictionForm').innerHTML=groups.map(g=>`<section class="round-block"><h3>${esc(g.round)} — ${g.count} partidos</h3>${g.alert?'<div class="notice">Error de data: faltan partidos en esta ronda.</div>':''}${g.matches.map(m=>{let p=predictions[m.matchId]||{},c=completion(m),a=pickValue(m,'teamA'),b=pickValue(m,'teamB');return`<article class="match-card ${c.cls}" data-card="${m.matchId}"><div class="match-top"><span>${esc(m.round)}</span><b>Partido FIFA ${esc(m.fifaMatchNumber||m.matchId)}</b></div><h3>${esc(a)} <em>vs</em> ${esc(b)}</h3><p class="muted">${fmt(m.date)||'Fecha por confirmar'}${m.venue?' · '+esc(m.venue):''}</p><div class="winner-picks"><button type="button" class="team-pick ${p.winner===a?'selected':''}" data-mid="${m.matchId}" data-field="winner" data-value="${esc(a)}">Clasifica ${esc(a)}</button><button type="button" class="team-pick ${p.winner===b?'selected':''}" data-mid="${m.matchId}" data-field="winner" data-value="${esc(b)}">Clasifica ${esc(b)}</button></div><div class="score-grid"><label>Goles A<input type="number" min="0" data-mid="${m.matchId}" data-field="scoreA" value="${esc(p.scoreA??'')}"></label><label>Goles B<input type="number" min="0" data-mid="${m.matchId}" data-field="scoreB" value="${esc(p.scoreB??'')}"></label></div><div class="status-pill ${c.cls}">${c.txt}</div></article>`}).join('')}</section>`).join('');document.querySelectorAll('[data-mid]').forEach(el=>{el.onclick=el.oninput=handleInput})}
function handleInput(e){const el=e.currentTarget,mid=el.dataset.mid,field=el.dataset.field;predictions[mid]||={};predictions[mid][field]=el.dataset.value??el.value;rebuildBracketFromPredictions();renderAll();updateDraftStatus('Cambios sin guardar');clearTimeout(window.__draftTimer);window.__draftTimer=setTimeout(saveDraft,350)}
function renderBracket(){const grouped=roundOrder.map(r=>[r,bracketMatches.filter(m=>m.round===r)]);$('bracketCanvas').innerHTML=grouped.map(([r,ms])=>`<div class="bracket-col"><h3>${esc(shortRound(r))} — ${ms.length} partidos</h3>${ms.length<expectedRoundCounts[r]?'<div class="notice">Error de data: faltan partidos en esta ronda.</div>':''}${ms.map(m=>{let p=predictions[m.matchId]||{},c=completion(m),a=pickValue(m,'teamA'),b=pickValue(m,'teamB');return`<article class="bracket-match ${c.cls}"><div class="match-top"><span>${esc(m.matchId)}</span><b>${c.cls==='complete'?'✓':'·'}</b></div><button class="bracket-team ${p.winner===a?'selected':''}" data-mid="${m.matchId}" data-field="winner" data-value="${esc(a)}">${esc(a)}</button><button class="bracket-team ${p.winner===b?'selected':''}" data-mid="${m.matchId}" data-field="winner" data-value="${esc(b)}">${esc(b)}</button></article>`}).join('')}</div>`).join('');document.querySelectorAll('.bracket-team').forEach(b=>b.onclick=handleInput)}
function renderLeaderboard(){let rows=state.leaderboard||[];$('leaderboard').innerHTML=`<table class="leaderboard-table"><thead><tr><th>Puesto</th><th>Número</th><th>Nombre</th><th>Puntos</th><th>Exactos</th><th>Ganadores</th><th>Versiones enviadas</th></tr></thead><tbody>${rows.map(r=>`<tr class="rank-${r.position}"><td>${r.position<=3?['🥇','🥈','🥉'][r.position-1]:r.position}</td><td>${esc(r.playerNumber)}</td><td><button class="linklike" data-player="${esc(r.playerNumber)}">${esc(r.playerName)}</button></td><td><b>${r.totalPoints}</b></td><td>${r.exactHits}</td><td>${r.winnerHits}</td><td>${r.versions||''}</td></tr>`).join('')||'<tr><td colspan="7">Sin registros todavía.</td></tr>'}</tbody></table>`;document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>showDetail(rows.find(r=>r.playerNumber===b.dataset.player)))}
function showDetail(r){$('detail').classList.remove('hidden');$('detail').innerHTML=`<h2>Ficha del jugador</h2><p><b>${esc(r.playerName)}</b> · #${esc(r.playerNumber)}</p><p>${r.totalPoints} pts · ${r.exactHits} exactos · ${r.winnerHits} ganadores · ${r.versions||0} versiones</p>`}
function renderHistory(rows){$('historyRows').innerHTML=`<table class="leaderboard-table"><thead><tr><th>Versión</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.version}</td><td>${fmt(r.timestamp)}</td><td>${r.validBeforeDeadline?'válida':'fuera de tiempo'}</td></tr>`).join('')||'<tr><td colspan="3">Sin guardados.</td></tr>'}</tbody></table>`}
async function savePrediction(){if(!beforeDeadline())return show($('notice'),`El plazo para enviar quinielas cerró el ${fmt(state.deadline||CFG.DEADLINE)}.`);let r=await api({action:'submitPrediction',playerNumber:currentUser.playerNumber,password:playerPassword,predictions});if(!r.ok)return show($('notice'),r.error||'No se pudo guardar.');state.leaderboard=r.leaderboard||state.leaderboard;store.del(`draft-${currentUser.playerNumber}`);updateDraftStatus('Última versión enviada');show($('notice'),'¡Tu quiniela quedó guardada!');$('receipt').classList.remove('hidden');$('receipt').innerHTML=`<h2>¡Tu quiniela quedó guardada!</h2><p><b>Nombre:</b> ${esc(currentUser.playerName)} · <b>Número:</b> #${esc(currentUser.playerNumber)}</p><p><b>Código de registro:</b> ${esc(r.submissionId)}</p><p><b>Fecha/hora:</b> ${fmt(r.timestamp)}</p><p><b>Estado:</b> ${r.validBeforeDeadline?'válida':'fuera de tiempo'}</p>`;let st=await api({action:'getPlayerState',playerNumber:currentUser.playerNumber,password:playerPassword});if(st.ok){renderHistory(st.history||[]);state.leaderboard=st.leaderboard||state.leaderboard;renderLeaderboard()}}
$('loginTab').onclick=()=>{$('loginForm').classList.remove('hidden');$('registerForm').classList.add('hidden');$('loginTab').classList.add('primary');$('registerTab').classList.remove('primary')};
$('registerTab').onclick=()=>{$('registerForm').classList.remove('hidden');$('loginForm').classList.add('hidden');$('registerTab').classList.add('primary');$('loginTab').classList.remove('primary')};
$('loginForm').onsubmit=async e=>{e.preventDefault();playerPassword=$('loginPassword').value;let r=await api({action:'loginPlayer',playerNumber:$('loginNumber').value,password:playerPassword});r.ok?enterApp(r):show($('authNotice'),r.error)};
$('registerForm').onsubmit=async e=>{e.preventDefault();if($('registerPassword').value!==$('registerConfirm').value)return show($('authNotice'),'Las contraseñas no coinciden.');playerPassword=$('registerPassword').value;let r=await api({action:'registerPlayer',playerName:$('registerName').value,playerNumber:$('registerNumber').value,password:playerPassword});r.ok?enterApp(r):show($('authNotice'),r.error)};
$('saveBtn').onclick=savePrediction;$('logoutBtn').onclick=()=>{store.del('quinielaCurrentUser');location.reload()};
$('showMineBtn').onclick=()=>show($('notice'),'Tu última quiniela válida está cargada automáticamente; si hay borrador local, se usa hasta que envíes.');$('viewFormBtn').onclick=()=>{$('formView').classList.remove('hidden');$('bracketView').classList.add('hidden')};
$('viewBracketBtn').onclick=()=>{$('bracketView').classList.remove('hidden');$('formView').classList.add('hidden')};
$('leaderboardRefresh').onclick=async()=>{let st=await api({action:'getPlayerState',playerNumber:currentUser.playerNumber,password:playerPassword});if(st.ok){state.leaderboard=st.leaderboard;renderLeaderboard()}};init().catch(e=>show($('authNotice'),e.message));
